apiVersion: apps/v1
kind: Deployment
metadata:
  name: chromium-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chromium-app
  template:
    metadata:
      labels:
        app: chromium-app
    spec:
      containers:
      - name: chromium-app-container
        image: 192.168.49.2:30154/osama/neko:chromium
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        - name: udp-port-0
          containerPort: 55000
        - name: udp-port-1
          containerPort: 55001
        - name: udp-port-2
          containerPort: 55002
        - name: udp-port-3
          containerPort: 55003
        - name: udp-port-4
          containerPort: 55004
        - name: udp-port-5
          containerPort: 55005
        - name: udp-port-6
          containerPort: 55006
        - name: udp-port-7
          containerPort: 55007
        - name: udp-port-8
          containerPort: 55008
        - name: udp-port-9
          containerPort: 55009
        env:
        - name: NEKO_SCREEN
          value: "1920x1080@30"
        - name: NEKO_EPR
          value: "55000-55009"
        - name: NEKO_NAT1TO1
          value: ""
        - name: NEKO_ICELITE
          value: "true"
        - name: NEKO_MAX_FPS
          value: "25"
        - name: NEKO_PASSWORD
          value: "osama"
        - name: NEKO_PASSWORD_ADMIN
          value: "admin"
        - name: NEKO_IMPLICIT_CONTROL
          value: "true"
      imagePullSecrets:
      - name: my-registry-secret
