apiVersion: v1
kind: Service
metadata:
  name: chromium-app-tcp-service
spec:
  type: NodePort  # Change from LoadBalancer to NodePort
  selector:
    app: chromium-app
  ports:
    - protocol: TCP
      name: http
      port: 8081         # Port that the service will expose
      targetPort: 8080   # Port that your application is running on
      nodePort: 30010    # Optional: Specify a NodePort within the valid range (30000-32767)
