apiVersion: v1
kind: Service
metadata:
  name: neko-app-tcp-service
spec:
  type: LoadBalancer  # Changed from NodePort to LoadBalancer
  selector:
    app: neko-app     # Updated app name
  ports:
    - protocol: TCP
      name: http
      port: 8081         # Port that the service will expose
      targetPort: 8080   # Port that your application is running on
